### ISSUE TITLE
Saving Upcoming Challenge

### ISSUE THREAD

**Issue by baybatu** [ChallengeHunt/challengehunt#1]
It would be nice feature to save upcoming event that i want to join for notify us later. Thank you.

**Comment by architv** [comment]
Hi @baybatu ,

This is definitely our top priority for the next release. Thanks for your feedback!

**Comment by architv** [comment]
We have added the support for saving the challenge in your Google Calendar. Just click on the bell icon in the upcoming tab. Closing the issue for now.

**Comment by baybatu** [comment]
It looks nice. Thank you.
