### ISSUE TITLE
False contest showing in the extension

### ISSUE THREAD

**Issue by deepak042** [ChallengeHunt/challengehunt#11]
https://www.codechef.com/UEMK16TS
This contest does not exist but it is shown in the extension.
![gt](https://cloud.githubusercontent.com/assets/17472951/16979160/3a74120e-4e7d-11e6-88a0-0b96c2f14934.PNG)

**Comment by sukhmeet032795** [comment]
Hi,

Thanks for bringing it to our attention. We will check from our end and rectify the issue asap.

**Comment by sukhmeet032795** [comment]
@deepak042 Sorry for the late reply. We looked into it but forgot to reply. Our data is being fetched from an api which gets updated at regular intervals. As soon as you relaunch the extension and api gets updated, the finished or non occuring challenges disappear, showing only the relevant challenges.
