### ISSUE TITLE
REg Time Zones

### ISSUE THREAD

**Issue by tirupatihemanth** [ChallengeHunt/challengehunt#3]
If you can show timings based on timezone of the user that would be a great plus. Thank You

**Comment by architv** [comment]
Hi @tirupatihemanth !

Thanks for using Challenge Hunt!

We already show the challenges timings based on the user's timezone. I am sorry I couldn't get you. Could you please elaborate a bit?

**Comment by tirupatihemanth** [comment]
Yeah, Actually Your extension get's timezone based on the System Time Zone. My System Time Zone was wrong so I was getting wrong timings for contests. I realized that and changed my Time Zone it started working fine.

There is no fault in the extension in this regard. However you could improve the extension by detecting Time Zone from IP and not just going only by system Time Zone.  I think this is a valid improvement because many people who use Linux distro just forget about the time zone the system is in even though it might show correct time. 

Thank You,

**Comment by architv** [comment]
Yes, that can be used as alternative to the existing system. If we observe any more such issues, we'll do that. Thanks! For now, I am closing the issue.
