### ISSUE TITLE
Why Update?

### ISSUE THREAD

**Issue by SumeetVarma** [ChallengeHunt/challengehunt#5]
Previously, all the 'upcoming' contests were sorted on the time and date they were scheduled to be. Now they are first sorted on the host website and then on the time. This isn't good because I am interested in knowing the upcoming contest irrespective of what website they are on. I don't want to scroll a list of 25 noob college hackerearth contests to see time and date of next topcoder srm or codeforces round.

**Comment by architv** [comment]
Hi @SumeetVarma,

We have been having some problems with our API. This would be fixed soon. Sorry for that.

**Comment by architv** [comment]
Should be fixed now. By the way, we are planning an update to Challenge Hunt to fix all the bugs and with a new design so that such problems wouldn't occur.
