### ISSUE TITLE
Not working today?

### ISSUE THREAD

**Issue by derekhh** [ChallengeHunt/challengehunt#6]
It seems the Chrome extension is no longer working today...

![image](https://cloud.githubusercontent.com/assets/1497445/11258703/6d0aa2d8-8e10-11e5-98f6-25f11d82662b.png)

**Comment by architv** [comment]
Hi @derekhh 

Sorry, it was down for a while. It's up and working now. Let me know if you face the issue again.

**Comment by derekhh** [comment]
It's working now. Thanks! :)
